version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  build:
    working_directory: ~/FarmersMarket
    docker:
      - image: circleci/node:14 # Use a Node.js image for building React app
    steps:
      - checkout
      - setup_remote_docker 
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME
      - run:
          name: run-docker-image
          command: docker run -p 8443:8443 -d $IMAGE_NAME # Run React app on port 8443


  deploy:
    docker:
      - image: circleci/node:14 # Use Node.js image for deployment
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export CONTAINER_NAME=\"$CONTAINER_NAME\"; export IMAGE_NAME=\"$IMAGE_NAME\"; sudo rm -rf FarmersMarket/; git clone https://github.com/DecGillen/FarmersMarket; source FarmersMarket/deploy.sh"
